/**
 * Prepare customer-authored runtime inputs for the selected content backend.
 *
 * Self-hosted builds preserve the historical embedded TypeScript maps. Managed
 * builds instead emit immutable static assets and fixed-size empty module maps,
 * keeping Worker code size independent of the number or size of docs pages.
 * Generated output is ignored so authors continue editing only the source.
 */

import {
  mkdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import path from 'node:path'
import { compile } from '@mdx-js/mdx'
// tsx exposes these extensionless TypeScript modules through CJS interop when
// this generator runs as ESM. Their declared shape still has named exports.
// @ts-expect-error -- runtime interop intentionally provides the default object
import frontmatterModule from '../src/lib/frontmatter'
// @ts-expect-error -- runtime interop intentionally provides the default object
import rehypeModule from '../src/mdx/rehype'
// @ts-expect-error -- runtime interop intentionally provides the default object
import remarkModule from '../src/mdx/remark'
// tsx exposes this extensionless TypeScript module through CJS interop when
// the generator runs as ESM. Its declared shape still has named exports.
// @ts-expect-error -- runtime interop intentionally provides the default object
import runtimeContentFilesModule from './lib/runtime-content-files'
import type { RuntimeSourceMap } from './lib/runtime-content-files'

const { parseFrontmatter } = frontmatterModule as unknown as typeof import('../src/lib/frontmatter')
const { rehypePlugins } = rehypeModule as unknown as typeof import('../src/mdx/rehype')
const { remarkPlugins } = remarkModule as unknown as typeof import('../src/mdx/remark')
const {
  collectRuntimeContentFiles,
  removeManagedContentAssets,
  writeManagedContentAssets,
} = runtimeContentFilesModule as unknown as typeof import('./lib/runtime-content-files')

const projectRoot = process.cwd()
const outputPath = path.join(projectRoot, 'src/generated/runtime-sources.ts')
const compiledDocsDirectory = path.join(projectRoot, 'src/generated/runtime-docs')
const compiledDocsIndexPath = path.join(projectRoot, 'src/generated/runtime-docs.ts')
const isManagedAssetsMode = process.env.THALLY_CONTENT_SOURCE?.trim().toLowerCase() === 'assets'
// A previous assets-mode run lives under public/ and would otherwise inventory
// itself recursively. Clear the reserved generated tree before every scan.
removeManagedContentAssets(projectRoot)
const authoredSources = collectRuntimeContentFiles(projectRoot)
// Managed releases read every authored input through ASSETS. Nothing authored
// may leak into these maps, otherwise bundle size resumes growing with content.
const embeddedSources: RuntimeSourceMap = isManagedAssetsMode ? {} : authoredSources

function writeRuntimeSourceMap(sources: Readonly<RuntimeSourceMap>): void {
  mkdirSync(path.dirname(outputPath), { recursive: true })
  writeFileSync(
    outputPath,
    `/** Generated by scripts/build-runtime-sources.mts. Do not edit. */\n` +
      `export interface RuntimeSourceEntry { content: string; modifiedAtMs: number }\n` +
      `export const runtimeSources: Readonly<Record<string, RuntimeSourceEntry>> = ${JSON.stringify(
        sources,
      )}\n`,
    'utf8',
  )
}

const snippetImportPattern = /^\s*import\s+\{([^}]+)\}\s+from\s+['"]\/snippets\/[^'"]+['"];?\s*$/gm

/**
 * Compile MDX while the build still has Node privileges.
 *
 * next-mdx-remote evaluates generated JavaScript with `new Function` at request
 * time. Workerd intentionally disallows that. Static generated modules retain
 * the same remark/rehype pipeline and component injection contract without an
 * unsafe-eval binding in production.
 */
async function writeCompiledDocs(): Promise<number> {
  rmSync(compiledDocsDirectory, { recursive: true, force: true })
  mkdirSync(compiledDocsDirectory, { recursive: true })

  const imports: Array<string> = []
  const records: Array<string> = []
  const mdxSources = Object.entries(embeddedSources).filter(([filePath]) =>
    filePath.endsWith('.mdx'),
  )

  for (const [filePath, entry] of mdxSources) {
    const index = records.length
    const moduleName = `RuntimeDoc${index}`
    const frontmatterName = `RuntimeFrontmatter${index}`
    const modulePath = path.join(compiledDocsDirectory, `doc-${index}.tsx`)
    const parsed = parseFrontmatter(entry.content)
    const mdxSource = parsed.content.replace(snippetImportPattern, '')
    let program
    try {
      program = await compile(mdxSource, {
        outputFormat: 'program',
        remarkPlugins,
        rehypePlugins,
      })
    } catch (error) {
      throw new Error(
        `Failed to compile runtime MDX ${filePath}: ${error instanceof Error ? error.message : String(error)}`,
        { cause: error },
      )
    }

    writeFileSync(
      modulePath,
      `// @ts-nocheck -- generated MDX program\n${String(program)}\n` +
        `export const frontmatter = ${JSON.stringify(parsed.data)} as const\n`,
      'utf8',
    )
    imports.push(
      `import ${moduleName}, { frontmatter as ${frontmatterName} } from './runtime-docs/doc-${index}'`,
    )
    records.push(
      `${JSON.stringify(filePath)}: { component: ${moduleName}, frontmatter: ${frontmatterName} }`,
    )
  }

  writeFileSync(
    compiledDocsIndexPath,
    `/** Generated by scripts/build-runtime-sources.mts. Do not edit. */\n` +
      `import type { ComponentType } from 'react'\n` +
      `${imports.join('\n')}\n` +
      `export interface PrecompiledRuntimeDoc {\n` +
      `  component: ComponentType<{ components?: Record<string, unknown> }>\n` +
      `  frontmatter: Readonly<Record<string, unknown>>\n` +
      `}\n` +
      `export const runtimeDocs: Readonly<Record<string, PrecompiledRuntimeDoc>> = {\n` +
      `  ${records.join(',\n  ')}\n` +
      `}\n`,
    'utf8',
  )
  return mdxSources.length
}

async function main(): Promise<void> {
  writeRuntimeSourceMap(embeddedSources)
  const contentAssetCount = isManagedAssetsMode
    ? Object.keys(writeManagedContentAssets(projectRoot, authoredSources).files).length
    : 0
  const compiledDocCount = await writeCompiledDocs()
  console.log(
    isManagedAssetsMode
      ? `[thally] runtime sources: emitted ${contentAssetCount} immutable content asset(s); embedded 0 file(s), compiled 0 MDX module(s)`
      : `[thally] runtime sources: embedded ${Object.keys(embeddedSources).length} file(s), compiled ${compiledDocCount} MDX module(s)`,
  )
}

void main()
